######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 18 13:46:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core

# Input
SOURCES += main.cpp
